schemaVersion: 2.1.0
metadata:
  name: quarkus-quickstart
  namespace: user1-devspaces
projects:
  - name: quarkus-quickstarts
    zip:
      location: 'http://devfile-registry.openshift-devspaces.svc:8080/resources/v2/quarkus-quickstarts.zip'
components: []
commands:
  - exec:
      commandLine: mvn package
      component: tools
      group:
        isDefault: true
        kind: build
      workingDir: '${PROJECTS_ROOT}/quarkus-quickstarts/getting-started'
    id: 1-package
  - exec:
      commandLine: 'mvn compile quarkus:dev'
      component: tools
      group:
        isDefault: true
        kind: run
      label: Start Development mode (Hot reload + debug)
      workingDir: '${PROJECTS_ROOT}/quarkus-quickstarts/getting-started'
    id: 2-startdev

